# Generated by Django 5.0.14 on 2025-08-04 12:43

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, unique=True)),
                ('targeted_domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('webhook_url', models.URLField()),
                ('auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_opted_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhishingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The suspicious URL submitted')),
                ('domain', models.CharField(blank=True, help_text='Extracted domain from the URL', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the issue')),
                ('screenshot', models.ImageField(blank=True, help_text='Optional screenshot evidence', null=True, upload_to='screenshots/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser_version', models.CharField(blank=True, help_text='Parsed browser version', max_length=100)),
                ('extension_version', models.CharField(blank=True, help_text='Reported extension version', max_length=50)),
                ('detected_by', models.CharField(default='unknown', max_length=100)),
                ('whois_registrar', models.CharField(blank=True, max_length=255, null=True)),
                ('whois_creation_date', models.DateField(blank=True, null=True)),
                ('whois_expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('report_submitted', 'Report Submitted'), ('extension_started', 'Extension Started'), ('error_occurred', 'Error Occurred'), ('feature_used', 'Feature Used'), ('domain_submitted', 'Domain Submitted')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True)),
                ('sent_to_virustotal', models.BooleanField(default=False)),
            ],
        ),
    ]
