# Generated by Django 5.2.4 on 2025-08-22 01:26

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, unique=True)),
                ('webhook_url', models.URLField()),
                ('lifetimetoken', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bank_webhook',
            },
        ),
        migrations.CreateModel(
            name='PhishingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('whois_data', models.JSONField(blank=True, null=True)),
                ('host_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'phishing_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['url'], name='phishing_re_url_bb06cf_idx'), models.Index(fields=['created_at'], name='phishing_re_created_902bc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhishingTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255, null=True)),
                ('schema_version', models.CharField(default='1.0.0', max_length=50)),
                ('details', models.JSONField(null=True)),
                ('normalized_summary', models.TextField(blank=True, null=True)),
                ('enriched_flags', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'phishing_telemetry',
                'indexes': [models.Index(fields=['source'], name='phishing_te_source_fc3464_idx')],
            },
        ),
    ]
