# Generated by Django 5.0.14 on 2025-07-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='The suspicious URL submitted')),
                ('description', models.TextField(blank=True, help_text='Optional description of the issue')),
                ('screenshot', models.ImageField(blank=True, help_text='Optional screenshot evidence', null=True, upload_to='screenshots/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('detected_by', models.CharField(default='unknown', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
