# Generated by Django 5.0.14 on 2025-07-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingreport',
            name='browser_version',
            field=models.CharField(blank=True, help_text='Parsed browser version', max_length=100),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='domain',
            field=models.CharField(blank=True, help_text='Extracted domain from the URL', max_length=255),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='extension_version',
            field=models.CharField(blank=True, help_text='Reported extension version', max_length=50),
        ),
    ]
