# Generated by Django 5.0.14 on 2025-08-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_phishingreport_browser_version_phishingreport_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishingreport',
            name='whois_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='whois_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phishingreport',
            name='whois_registrar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
