# Generated by Django 5.0.14 on 2025-08-02 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_phishingreport_whois_creation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('report_submitted', 'Report Submitted'), ('extension_started', 'Extension Started'), ('error_occurred', 'Error Occurred'), ('feature_used', 'Feature Used'), ('domain_submitted', 'Domain Submitted')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True)),
                ('sent_to_virustotal', models.BooleanField(default=False)),
            ],
        ),
    ]
